### PR TITLE
Hotline multiple numbers

### PR DESCRIPTION
**Pull request by sharett**
Added support for multiple hotline numbers.  Most files ended up being changed to accommodate this, so basically everything involving the hotline functionality needs to be tested.

### CODE REVIEW

**Comment by misplacedpriorities** [comment]
Code looks good, but that's without attempting to test. I like the idea floated at our last meeting of having regular users actually test this pull request on sharett's development server in order to give it a good workout; I feel that this is a changeset that would be dangerous for me to test in my usual way and sign off on if it passed.

If folks want me to test, that's completely fine, just let me know. But I definitely encourage the abovementioned approach.

**Comment by misplacedpriorities** [comment]
(Unrelated, but I don't believe I have another way to contact the group: My phone died, which means I don't have access to the usual methods of communication with the coding team or anyone else. I should have a working phone again by Wednesday morning the 25th at the latest.)

Due to the lack of other methods of communication for me for the moment, I thought I'd ask here: Where are we getting our CSS from, besides dashboard.css? I'm looking at working on the message box disallowing the selection of zero checkboxes in the modal call time dialog, and I see in the code I'd be modifying the use of div classes and roles that I don't see defined in dashboad.css.

**Comment by sharett** [comment]
Hi Chris - Thanks for the review!  Bob has agreed to test on the development server, and your testing would be most welcome as well. I've created a grain on Sandstorm called "Development server (Alex)" with the credentials.

With regard to CSS, we use Bootstrap (3.x version), https://getbootstrap.com/docs/3.3/

~Alex

**Comment by misplacedpriorities** [comment]
Changes test out well. I recommend it be merged if other testers have reported no issues.

**Pull request merged**
