### PR TITLE
Broadcast response closing

### PR DESCRIPTION
**Pull request by sharett**
Another one that I thought I had merged. Please review!

### CODE REVIEW

**Comment by misplacedpriorities** [comment]
Before I review this: I'm confused as to where in the GUI I'll see this change. What steps should I take as a tester to see how this works (and of course I'll try it without the changeset first, so as to compare)? Should get to this on Monday.

**Comment by sharett** [comment]
In order to see this in the GUI, you'll need to send a broadcast message that has a "Response requested?".  Then you'll be able to send updates to those who respond, and have the option to close the broadcast.

**Comment by misplacedpriorities** [comment]
OK, thanks; I'll go ahead and test it out as soon as I can get to it (probably not tonight).

**Comment by misplacedpriorities** [comment]
The "close" functionality works as intended according to my tests. Ready for merge.

**Pull request merged**
